[trap]
path = "src/LiquidityProtectionTrap.sol"
contract_name = "LiquidityProtectionTrap"

[network]
rpc_url = "https://rpc.hoodi.ethpandaops.io"
chain_id = 560048

[response]
# Replace with your deployed LiquidityWithdrawer address
response_contract = "0xYOUR_LIQUIDITY_WITHDRAWER_ADDRESS_HERE"
# Function signature matches emergencyWithdraw(address pair, uint256 amount)
response_function = "emergencyWithdraw(address,uint256)"

[deployment]
# Will be filled in after deployment
# address = ""
